---
version: 1.0.2
slug: microwakeword
name: microwakeword
description: microWakeWord using the Wyoming protocol
url: https://github.com/rhasspy/hassio-addons/tree/master/microwakeword
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
options:
  debug_logging: false
  custom_dir: ""
schema:
  debug_logging: bool 
  custom_dir: str
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
