---
version: 1.0.2
slug: microwakeword
name: microwakeword-custom_dir
description: microWakeWord using the Wyoming protocol
url: https://github.com/Mariuss811/hassio-addons-custom
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
options:
  debug_logging: false
  custom_dir: ""
schema:
  debug_logging: bool 
  custom_dir: str
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
map:
  - type: share
    read_only: False
  - type: config
    read_only: True
